from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import io

def generate_notes_pdf(lecture_title, lecture_subject, lecture_notes, lecture_date=None):
    """
    Generate a PDF document with lecture notes.
    
    Args:
        lecture_title (str): Title of the lecture
        lecture_subject (str): Subject/topic name
        lecture_notes (str): The notes content
        lecture_date (str): Date of the lecture (optional)
    
    Returns:
        bytes: PDF file content as bytes
    """
    # Create PDF buffer
    pdf_buffer = io.BytesIO()
    
    # Create PDF document
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch,
        title=f"{lecture_subject} - {lecture_title}"
    )
    
    # Get styles
    styles = getSampleStyleSheet()
    
    # Create custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=(255, 77, 79),  # Red color
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subject_style = ParagraphStyle(
        'CustomSubject',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=(100, 100, 100),
        spaceAfter=12,
        alignment=TA_CENTER,
        fontName='Helvetica'
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        leading=16,
        spaceAfter=10,
        alignment=TA_LEFT
    )
    
    # Build document content
    content = []
    
    # Title
    content.append(Paragraph(f"📚 {lecture_title}", title_style))
    content.append(Spacer(1, 0.2*inch))
    
    # Subject and date
    subject_text = f"{lecture_subject}"
    if lecture_date:
        subject_text += f" | {lecture_date}"
    content.append(Paragraph(subject_text, subject_style))
    content.append(Spacer(1, 0.3*inch))
    
    # Notes content
    # Clean up notes for PDF display
    notes_text = lecture_notes.replace('\n', '<br/>').replace('•', '•')
    content.append(Paragraph(notes_text, body_style))
    
    # Footer
    content.append(Spacer(1, 0.5*inch))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=(150, 150, 150),
        alignment=TA_CENTER
    )
    generated_text = f"Generated by Classmate AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    content.append(Paragraph(generated_text, footer_style))
    
    # Build PDF
    doc.build(content)
    
    # Get PDF bytes
    pdf_buffer.seek(0)
    return pdf_buffer.getvalue()


def generate_notes_word(lecture_title, lecture_subject, lecture_notes, lecture_date=None):
    """
    Generate a Word document with lecture notes.
    
    Args:
        lecture_title (str): Title of the lecture
        lecture_subject (str): Subject/topic name
        lecture_notes (str): The notes content
        lecture_date (str): Date of the lecture (optional)
    
    Returns:
        bytes: Word document file content as bytes
    """
    # Create Word document
    doc = Document()
    
    # Add title
    title = doc.add_heading(f"📚 {lecture_title}", level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_format = title.runs[0].font
    title_format.color.rgb = RGBColor(255, 77, 79)  # Red color
    
    # Add subject and date
    subject_para = doc.add_paragraph()
    subject_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subject_run = subject_para.add_run(lecture_subject)
    subject_run.font.size = Pt(14)
    subject_run.font.color.rgb = RGBColor(100, 100, 100)
    
    if lecture_date:
        subject_para.add_run(f" | {lecture_date}")
    
    # Add spacing
    doc.add_paragraph()
    
    # Add notes content
    # Split notes by lines and add as paragraphs
    for line in lecture_notes.split('\n'):
        if line.strip():
            # Check if it's a bullet point
            if line.strip().startswith('•') or line.strip().startswith('-'):
                p = doc.add_paragraph(line.strip(), style='List Bullet')
            else:
                p = doc.add_paragraph(line.strip())
            
            # Format text
            for run in p.runs:
                run.font.size = Pt(11)
                run.font.name = 'Calibri'
    
    # Add footer
    doc.add_paragraph()
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_para.add_run(f"Generated by Classmate AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(150, 150, 150)
    
    # Save to bytes buffer
    word_buffer = io.BytesIO()
    doc.save(word_buffer)
    word_buffer.seek(0)
    return word_buffer.getvalue()
